Add query proof
hashcloak/katzenmint-pki pull request #27
Opened 2021-05-06 17:26 UTC by greatect

Resolving part of issue #25:
* Use IAVL tree to maintain state and provide merkle proof
* Deal with app height, hash, epoch and put them into ABCI info
* Provide proofs inside ABCI query responses
* Add a test for posting document and querying documents with proof
* Add utilities for generating documents, but still not auto generated during the commit stage
* Remove duplicate signing/verification of document
* Refinement on storage keys
* Naming on error codes

2021-05-07 04:00 UTC, sc0Vu requested changes

2021-05-07 04:00 UTC, sc0Vu commented on util.go
> +func (state *KatzenmintState) documentForEpoch(epoch uint64) ([]byte, merkle.ProofOperator, error) {
IMHO we should put this function into state.go, If we only use this function in katzenmint state.

2021-05-07 04:00 UTC, sc0Vu commented on util.go
> +func (s *KatzenmintState) generateDocument() (*document, error) {
Same.

2021-05-11 07:48 UTC, greatect commented on helper.go
> +func CreateTestDescriptor(require *require.Assertions, idx int, layer int, epoch uint64) (*pki.MixDescriptor, []byte) {
Moved to a separate testutil package

2021-05-11 07:48 UTC, greatect commented on helper.go
> +func CreateTestDocument(require *require.Assertions, epoch uint64) (*s11n.Document, []byte) {
Moved to a separate testutil package

2021-05-15 13:49 UTC, sc0Vu approved these changes
LGTM

2021-05-17 08:21 UTC, merged